# Generated by Django 5.0.4 on 2024-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_board_lists_remove_list_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='board_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='list_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
